// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  hasSupabaseEnv,
  SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_URL,
  supabaseEnvError,
} from "./config";

function createMissingClient(message: string): SupabaseClient<Database> {
  const thrower = () => {
    throw new Error(message);
  };

  const proxy = new Proxy(thrower, {
    get: () => proxy,
    apply: thrower,
  });

  return proxy as unknown as SupabaseClient<Database>;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasSupabaseEnv
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      global: {
        headers: {
          Accept: "application/json",
        },
      },
    })
  : createMissingClient(
      supabaseEnvError ||
        "As variáveis do Supabase não foram configuradas para este ambiente.",
    );

if (!hasSupabaseEnv) {
  console.warn(
    "[Supabase] Variáveis de ambiente ausentes. Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY ou VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY.",
  );
}
